spring:
  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: d173137e871d96ad298bf43551057b2a
            redirect-uri: "http://localhost/oauth2/code/kakao" # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: cluv-2
          naver:
            client-id: mWhEBMW48WjO5vUihfQS
            client-secret: 2wvk8n8G7r
            redirect-uri: "http://localhost/login/oauth2/code/naver" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response